language: elixir

elixir:
  - '1.9.4'
otp_release:
  - '22.2'

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - _build

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

script:
  - mix test
  - mix dialyzer

# Leave only the .plt files in build
before_cache:
  - mix deps.clean --all --build
  - mix clean --build
